/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package App;

import Paneles.TextPrompt;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Fernando Amador
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    TextPrompt holder;

    public Login() {
        initComponents();
        holder = new TextPrompt("Nombre de usuario", txtNombre);
        holder = new TextPrompt("Contraseña", txtPassword);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bntIniciar_sesion = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        txtNombre = new javax.swing.JTextField();
        lblRecuperar = new javax.swing.JLabel();
        Mostrar_Ocultar = new javax.swing.JLabel();
        Registrarse = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inicio de Sesión");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(240, 128, 128));

        jLabel2.setFont(new java.awt.Font("Lucida Calligraphy", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Variedades & Modas ");

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Glenda's");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tailoring_icon.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(126, 126, 126))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(129, 129, 129))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/contact_user_icon.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/6973362_phone_user_communication_contact_icon.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/padlock_private_icon.png"))); // NOI18N

        bntIniciar_sesion.setBackground(new java.awt.Color(240, 128, 128));
        bntIniciar_sesion.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        bntIniciar_sesion.setForeground(new java.awt.Color(255, 255, 255));
        bntIniciar_sesion.setText("Iniciar Sesión");
        bntIniciar_sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntIniciar_sesionActionPerformed(evt);
            }
        });

        txtPassword.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPasswordKeyTyped(evt);
            }
        });

        txtNombre.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreFocusLost(evt);
            }
        });
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        lblRecuperar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblRecuperar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/secure_security_icon.png"))); // NOI18N
        lblRecuperar.setText("¿Olvidaste la contraseña?");
        lblRecuperar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRecuperarMouseClicked(evt);
            }
        });

        Mostrar_Ocultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eye_key.png"))); // NOI18N
        Mostrar_Ocultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Mostrar_OcultarMouseClicked(evt);
            }
        });

        Registrarse.setFont(new java.awt.Font("Arial Black", 2, 14)); // NOI18N
        Registrarse.setText("Registrarse");
        Registrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegistrarseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(168, 168, 168))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(bntIniciar_sesion, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                                    .addComponent(txtNombre)
                                    .addComponent(txtPassword)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(lblRecuperar)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Mostrar_Ocultar)
                                .addGap(85, 85, 85))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Registrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(159, 159, 159))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Mostrar_Ocultar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5))
                .addGap(29, 29, 29)
                .addComponent(bntIniciar_sesion, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Registrarse)
                .addGap(18, 18, 18)
                .addComponent(lblRecuperar)
                .addGap(26, 26, 26))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 855, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    
     boolean passwordVisible = false;
    String imagePath = "/img/eye_key.png";

    java.net.URL imgUrl = recuperarContra.class.getResource(imagePath);
    // Crear un ImageIcon con la ruta de la imagen
    ImageIcon icon = new ImageIcon(imgUrl);

   
    String imagePath1 = "/img/eye_password.png";

     java.net.URL imgUr2 = recuperarContra.class.getResource(imagePath1);
    // Crear un ImageIcon con la ruta de la imagen
    ImageIcon icon1 = new ImageIcon(imgUr2);

    private void Mostrar_OcultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Mostrar_OcultarMouseClicked

        if (passwordVisible)
        {
            txtPassword.setEchoChar('*');
            Mostrar_Ocultar.setIcon(icon);
        } else
        {
            txtPassword.setEchoChar((char) 0); // Muestra la contraseña
            Mostrar_Ocultar.setIcon(icon1);
        }
        passwordVisible = !passwordVisible;

        /*passwordVisible = !passwordVisible;
        if (passwordVisible) {
            txtPassword.setEchoChar((char) 0); // Muestra la contraseña en texto plano
        } else {
            txtPassword.setEchoChar('*'); // Encripta la contraseña
        }*/
    }//GEN-LAST:event_Mostrar_OcultarMouseClicked

    private void RegistrarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarseMouseClicked
        Crear_Usuario usu = new Crear_Usuario();
        usu.setVisible(true);
        usu.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_RegistrarseMouseClicked

    private void bntIniciar_sesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntIniciar_sesionActionPerformed
        try
        {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection conn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=GlendaDB;encrypt=true;trustServerCertificate=true;", "sa", "123456789");

            String nombreUsuario = txtNombre.getText(); // Nombre de usuario ingresado por el usuario
            char[] contrasenaChars = txtPassword.getPassword();
            String contrasena = new String(contrasenaChars); // Contraseña ingresada por el usuario

            PreparedStatement selectPs = conn.prepareStatement("SELECT * FROM Usuarios WHERE nombre_usuario = ? AND contrasena = ?");
            selectPs.setString(1, nombreUsuario);
            selectPs.setString(2, contrasena);

            ResultSet resultSet = selectPs.executeQuery();

            if (resultSet.next())
            {
                // El usuario y contraseña coinciden, el inicio de sesión es exitoso

                // Abre la ventana principal o cualquier otra ventana después de un inicio de sesión exitoso
                Menu menuPrincipal = new Menu(); // Crear una instancia del menu
                menuPrincipal.setVisible(true); // Mostrar el menu

                // Cerrar la ventana actual si es necesario
                dispose(); // Cierra la ventana actual (ventana de inicio de sesión)
            } else
            {
                // El usuario y/o contraseña son incorrectos
                JOptionPane.showMessageDialog(null, "Usuario y/o contraseña incorrectos");
            }

            // Cerrar recursos (result set, statement, conexión) aquí
        } catch (SQLException e)
        {
            JOptionPane.showMessageDialog(null, e.toString(), "Error de SQL", JOptionPane.ERROR_MESSAGE);
        } catch (ClassNotFoundException ex)
        {
            JOptionPane.showMessageDialog(null, "Error de conexión a la base de datos", "Error de Conexión", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_bntIniciar_sesionActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar(); // Obtener el carácter ingresado

        if (txtNombre.getText().isEmpty() && (Character.isWhitespace(c) || !Character.isLetter(c)))
        {
            evt.consume(); // Consumir el evento si es un espacio en blanco o no es una letra en la primera posición
        } else if (txtNombre.getText().length() >= 50)
        {
            evt.consume(); // Consumir el evento si se ha alcanzado la longitud máxima
        }


    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyTyped
        // TODO add your handling code here:

        char[] contrasena = txtPassword.getPassword();
        char c = evt.getKeyChar(); // Obtener el carácter ingresado

        if (contrasena.length == 0 && Character.isWhitespace(c))
        {
            evt.consume(); // Consumir el evento si es un espacio en blanco en la primera posición
        } else if (contrasena.length >= 12)
        {
            evt.consume(); // Consumir el evento si se ha alcanzado la longitud máxima
        }

        /*char[] passwordChars = txtPassword.getPassword();
        String password = new String(passwordChars);

        if (password.length() == 0 || password.trim().isEmpty()) {
            evt.consume(); // Consumir el evento si está vacío o contiene solo espacios
        } else if (password.length() < 8 || password.length() > 20) {
            evt.consume(); // Consumir el evento si la longitud está fuera del rango permitido
        } else if (!password.matches("^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,20}$")) {
            evt.consume(); // Consumir el evento si no cumple con los requisitos de contenido
        }*/
    }//GEN-LAST:event_txtPasswordKeyTyped

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed

    }//GEN-LAST:event_txtNombreActionPerformed

    private void lblRecuperarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRecuperarMouseClicked

        // Obtén el nombre de usuario del formulario de login actual
        String usuario = txtNombre.getText().trim();

        // Verifica si el usuario existe en la base de datos
        if (usuarioExiste(usuario))
        {
            // Si el usuario existe, continúa con el proceso de recuperación de contraseña

            // Crea una instancia del formulario recuperarContra
            recuperarContra r = new recuperarContra();

            // Establece el texto en el campo de texto del formulario recuperarContra
            r.txtNUsuario.setText("Restablecer contraseña de " + usuario);
            r.txtNombreR.setText(usuario);

            // Muestra el formulario recuperarContra y cierra el formulario de login actual
            r.setVisible(true);
            this.dispose();
        } else if (txtNombre.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Ingrese un nombre de usuario para poder restablecer la contraseña.", "Error", JOptionPane.ERROR_MESSAGE);

        } else
        {
            // Si el usuario no existe, muestra un mensaje de error
            JOptionPane.showMessageDialog(null, "El usuario no existe.", "Error", JOptionPane.ERROR_MESSAGE);

        }

        System.out.println("Valor de txtNombre: " + txtNombre.getText());

    }//GEN-LAST:event_lblRecuperarMouseClicked

    private boolean usuarioExiste(String usuario) {

        try (
                Connection conn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=GlendaDB;encrypt=true;trustServerCertificate=true;", "sa", "123456789"); PreparedStatement stmt = conn.prepareStatement("SELECT COUNT(*) FROM Usuarios WHERE nombre_usuario = ?"))
        {

            stmt.setString(1, usuario);
            ResultSet resultSet = stmt.executeQuery();

            if (resultSet.next())
            {
                int count = resultSet.getInt(1);
                return count > 0; // Devuelve true si el usuario existe
            }

        } catch (SQLException e)
        {
            e.printStackTrace();
        }

        return false; // En caso de error, devuelve false por precaución
    }

    private void txtNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreFocusLost

    }//GEN-LAST:event_txtNombreFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Mostrar_Ocultar;
    private javax.swing.JLabel Registrarse;
    private javax.swing.JButton bntIniciar_sesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JLabel lblRecuperar;
    public javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
